<?php

define("MAILCHIMP_API_KEY", "46f81330fbece4a8daf24babf878c039-us2");

/**
 * Implements hook_menu().
 */
function runriot_mailinglist_signup_menu() {
  $items = array();

  $items['signup/mailinglist/%'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('runriot_mailinglist_signup_form', 2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['rr/mailinglist/%ctools_js/%'] = array(
    'page callback' => 'runriot_mailinglist_signup_callback',
    'page arguments' => array(2,3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Helper function to make a link.
 */
function _runriot_mailinglist_signup_make_link($link_text = '') {
  // Set a default value if no text in supplied.
  if (empty($link_text)) {
    $link_text = 'Modal';
  }

  return '<div id="magical-modal-link">' . l($link_text, 'rr/mailinglist/nojs/21', array('attributes' => array('class' => 'ctools-use-modal waitinglist-signup'))) . '</div>';
}

/**
 * An example page.
 */
function runriot_mailinglist_signup_page() {
  // Load the modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
  return _runriot_mailinglist_signup_make_link('Magical modal');
}

/**
 * Ajax menu callback.
 */
function runriot_mailinglist_signup_callback($ajax, $nid) {

  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');

    $form_state = array(
      'ajax' => TRUE,
      'title' => t('Sign up to our waiting list'),
      'nid' => $nid,
    );

    // Use ctools to generate ajax instructions for the browser to create
    // a form in a modal popup.
    $output = ctools_modal_form_wrapper('runriot_mailinglist_signup_form', $form_state);

    // If the form has been submitted, there may be additional instructions
    // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }

    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return drupal_get_form('runriot_mailinglist_signup_form', $nid);
  }
}

/**
 * Drupal form to be put in a modal.
 */
function runriot_mailinglist_signup_form($form, $form_state, $nid = FALSE) {

  $form = array();

  if (!$nid && !isset($form_state['nid'])) {
      $form['title'] = array(
    '#markup' => '<p>Sorry!  We can\'t load this form right now, please try again</p>',
  );
  }

  $form['title'] = array(
    '#markup' => '<h2>Thanks for joining up to our waiting list</h2><p>We\'ll let
    you know about any availability, and further courses</p>',
  );

 $form['close'] = array(
    '#markup' => '<h2>Thanks for joining up to our waiting list</h2><p>We\'ll let
    you know about any availability, and further courses</p>',
  );

  $form['firstname'] = array(
    '#type' => 'textfield',
    '#title' => t('Firstname'),
    '#required' => TRUE,
  );

  $form['surname'] = array(
    '#type' => 'textfield',
    '#title' => t('Surname'),
    '#required' => TRUE,
  );
  $form['dob'] = array(
    '#type' => 'textfield',
    '#title' => t('D.O.B'),
    '#required' => FALSE,
    '#description' => t('Please enter your d.o.b in the format dd/mm/yyyy'),
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email address'),
    '#required' => TRUE,
  );
  $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone number'),
    '#required' => FALSE,
  );
  $form['occupation'] = array(
    '#type' => 'textfield',
    '#title' => t('Occupation'),
    '#required' => FALSE,
  );
  $form['postcode'] = array(
    '#type' => 'textfield',
    '#title' => t('Postcode'),
    '#required' => FALSE,
  );

  $form['tickets'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(array(t('Full price'), t('Concessionary price'))),
    '#title' => t('Ticket option'),
  );
  $form['required'] = array(
    '#markup' => '<p>*Required fields</p>',
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => isset($form_state['nid']) ? $form_state['nid'] : $nid,
  );

  $form['tandcs'] = array(
    '#markup' => '<p>Thank you for joining us. Run-Riot Projects will process your data in accordance with the Data Protection Act 1998. For more information please refer to our privacy policy.</p>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Join waiting list'),
  );

 $form['close'] = array(
    '#markup' => '<div id="modal-close-button"><span class="ctools-close-modal"></span>
  <a href="#" class="ctools-close-modal">Close [x]</a></div>'
  );

  return $form;
}

/**
 * Drupal form submit handler.
 */
function runriot_mailinglist_signup_form_submit(&$form, &$form_state) {

  $node = node_load($form_state['values']['nid']);
  $mailchimp_id = field_get_items('node', $node, 'field_mailchimp_list_id');

  if (!isset($mailchimp_id[0]) || !isset($mailchimp_id[0]['value'])) {
    $output = '<div class="rrmodal-content"><h2>There\'s been a problem with the sign up.
    Please try again</h2>';
    $output .= '<span class="ctools-close-modal"></span>
  <a href="#" class="ctools-close-modal">Close [x]</span></div>';

    $form_state['ajax_commands'][] = ajax_command_replace('#modal-content', $output);
    return;
  }

    require_once('includes/Mailchimp.php');

  $mailchimp = new Mailchimp(MAILCHIMP_API_KEY, array("debug" => TRUE));

  $ticket_value = '';
  if ($form_state['values']['tickets']['Full price']
    && $form_state['values']['tickets']['Concessionary price']) {
    $ticket_value = "Either";
  } elseif ($form_state['values']['tickets']['Concessionary price']) {
    $ticket_value = "Concessions";
  } elseif ($form_state['values']['tickets']['Full price']) {
    $ticket_value = "Full";
  }

  $merge_vars = array(
    "FNAME" => $form_state['values']['firstname'],
    "LNAME" => $form_state['values']['surname'],
    "MMERGE3" => $ticket_value,
    "DOB" => $form_state['values']['dob'],
    "PHONE" => $form_state['values']['phone'],
    "OCCUPATION" => $form_state['values']['occupation'],
    "POSTCODE" => $form_state['values']['postcode'],
  );
  mailchimp_subscribe(
    $mailchimp_id[0]['value'],
    $form_state['values']['email'],
    $merge_vars,
    $double_optin = FALSE,
    $confirm = TRUE,
    $format = 'html',
    $update_existing = TRUE,
    $replace_interests = TRUE
  );

  // $outcome = $mailchimp->lists->subscribe(
  //   $mailchimp_id[0]['value'],
  //   array("email" => $form_state['values']['email']),
  //   $merge_vars,
  //   $email_type='html',
  //   $double_optin=true,
  //   $update_existing=true,
  //   $replace_interests=true,
  //   $send_welcome=true
  // );

  $output = '<div class="rrmodal-content"><h2>Thanks for signing up</h2><p>You should receive
  an email confirming your subscription.  Please follow the link in that email to complete your sign up</p>';
  $output .= '<span class="ctools-close-modal"></span>
<a href="#" class="ctools-close-modal">Close.</span></div>';

  $form_state['ajax_commands'][] = ajax_command_replace('#modal-content', $output);
}



/**
 * Drupal form to be put in a modal.
 */
function runriot_mailinglist_footer_signup_form($form, &$form_state) {
  $form = array();

  $form['firstname'] = array(
    '#type' => 'textfield',
    '#title' => t('Firstname'),
    '#required' => TRUE,
  );

  $form['surname'] = array(
    '#type' => 'textfield',
    '#title' => t('Surname'),
    '#required' => TRUE,
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email address'),
    '#required' => TRUE,
  );

  $form['list'] = array(
    '#type' => 'checkboxes',
    '#options' => array(
      "ec32e24507" => t('Run-Riot Projects'),
      "b193eac482" => t('Run-Riot Magazine'),
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Join us'),
  );

  return $form;
}

function runriot_mailinglist_footer_signup_form_submit(&$form, &$form_state) {

  require_once('includes/Mailchimp.php');
  $mailchimp = new Mailchimp(MAILCHIMP_API_KEY, array("debug" => FALSE));

  $merge_vars = array(
    "FNAME" => $form_state['values']['firstname'],
    "LNAME" => $form_state['values']['surname'],
  );

  foreach ($form_state['values']['list'] as $id => $list) {
    if (!$list)  {
      continue;
    }

    $outcome = $mailchimp->lists->subscribe(
      $list,
      array("email" => $form_state['values']['email']),
      $merge_vars,
      $email_type='html',
      $double_optin=true,
      $update_existing=true,
      $replace_interests=true,
      $send_welcome=true
    );
  // mailchimp_subscribe(
  //   $list,
  //   $form_state['values']['email'],
  //   $merge_vars,
  //   $double_optin = FALSE,
  //   $confirm = TRUE,
  //   $format = 'html',
  //   $update_existing = TRUE,
  //   $replace_interests = TRUE
  // );
    watchdog("runriot_mailinglist_signup", "mailing chimp sign !singup",
      array("!singup" => print_r($outcome,1)));
  }
  // drupal_set_message("Thanks for signing up to our mailing list!");
  $form_state['redirect'] = 'signup/thanks';
}
